### ISSUE TITLE
Suggestion: Allow Spear Auto Pick Up even when Auto Pick Up is turned off

### ISSUE THREAD

**Issue by xerberus333** [Goldenrevolver/ValheimSpearModsAndFriends#4]
I'm sorry for adding this under issues. Your mod is working perfectly as intended and is an essential QoL feature. I just didn't know anywhere else to maybe let my voice be heard, other than the git you linked under your mod page. I've been experiencing some inconvenience regarding my specific setup. I hope you'll indulge me explaining:

I can very often accidentally pick up random crap (greydwarf drops, rocks, etc.), which will take up the hotbar slot that was supposed to be reserved for my spear. This has led to numerous instances where pressing my hotkey no longer equips the spear, and I do a clumsy scramble through my inventory ui mid combat. I figured turning off auto pick up would fix this, but this means I can't just auto pick my spear anymore either.

You might be asking, "what about setting the auto retrieve timer to 1-5 seconds so that you don't need to worry about it?" I have mine set to 10-30 seconds, because I feel it's fair to have to run around the combat area and have to scramble to get it if I miss. If I set the cooldown to something really low, it feels like I don't need my bow anymore, as the spear is pretty much an infinite arrow version with zero speed penalty and only slightly worse bullet drop.

**Comment by Goldenrevolver** [comment]
your gameplay issue makes perfect sense. it does sound like you are using a mod that makes all items get added into your inventory from top to bottom. the base game only adds tools and weapons to the hotbar first, and adds all other items to the lowest row of the inventory first (bottom to top). that would eleviate this issue unless your inventory is completely full (in which case you cannot pick up the spear anyway). I will still consider your suggestion, the next time I push an update for this mod. please also consider the option of disabling that mod feature. as you mentioned, with how many trash item drops this game has, there was a reason irongate made those get added bottom to top instead of into the hotbar

also if you want to reach me more reliably, feel free to message me in the comment section of the equivalent nexusmods page of a thunderstore mod, or on discord
